### PR TITLE
Update help link

### PR DESCRIPTION
**Pull request by mdandrad**
#### Story Link
Update Help Links EDX-467

#### PR Description

Updating Help Link to New Site

#### Type of change

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X ] Documentation Change

#### How to test?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configurations.

- [ ] Test A
- [ ] Test B

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by pjamason** [comment]
@tasawernawaz looks like this test failed: https://jens-learnx-dev.ucsd.edu/job/edx-platform-python-pipeline-pr/lastFailedBuild/testReport/lms.djangoapps.branding.tests.test_page/PreRequisiteCourseCatalog/Run_Tests___lms_unit___test_course_with_prereq/

i don't think maria's change would cause this test to fail, and we'd like to get this change into monday's DEV release - let us know how you'd like to proceed.  thanks!

**Comment by tasawernawaz** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by tasawernawaz** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
