### PR TITLE
Fix failing unit tests

### PR DESCRIPTION
**Pull request by danialmalik**
#### Story Link
https://edlyio.atlassian.net/browse/EDE-327

#### PR Description

Fix the currently failing unit tests.

#### Type of change

Please select the options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

### CODE REVIEW

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
paver run pythn

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
