### PR TITLE
EDE-306: Rebase with ironwood.master

### PR DESCRIPTION
**Pull request by danialmalik**
#### Story Link
https://edlyio.atlassian.net/browse/EDE-306

#### PR Description

Rebase our branches with updated `openedx-release/ironwood.master`  branch from Open edX repo.

#### Type of change

Please select the options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by danialmalik** [comment]
jenkins run all

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by tasawernawaz** [comment]
@danialmalik I don't know how we can review this PR. Just make sure two things,

- This change is not breaking anything,
- Tests should pass.

**Comment by danialmalik** [comment]
@tasawernawaz I've run the tests against the PR, and the only tests failing are ones failing due to the "certificate" content changed. This PR does not increase the failed tests count in our current dev branch (i.e. 42).

**Pull request merged**
