### PR TITLE
Bug Fix: release-2020-05-06

### PR DESCRIPTION
**Pull request by imhassantariq**
#### PR Description
Bug Fix: release-2020-05-06

Fixes a bug where putting `Space` at the start or end of the password occurs Bug "NoneType" object has not backend.

#### Type of change

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by imhassantariq** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by imhassantariq** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
