### PR TITLE
test coverage

### PR DESCRIPTION
**Pull request by sheralim012**
#### Story Link
[https://edlyio.atlassian.net/browse/EDE-1046](https://edlyio.atlassian.net/browse/EDE-1046)

#### PR Description

test coverage on jenkins is 9% and it should be at least 95 %

#### Type of change

Please select the options that are relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

#### How to test?

- [ ] go to jenkins
- [ ] open any build
- [ ] open coverage report
- [ ] it should be at least 95%

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by sheralim012** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by sheralim012** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by sheralim012** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by sheralim012** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Review by imhassantariq — APPROVED** [review]

**Pull request merged**
