### PR TITLE
[DON'T MERGE] initial commit for jenkin tests

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### Story Link
[Jenkins tests](https://edlyio.atlassian.net/browse/EDS-219)

#### PR Description

This PR is meant to check if Jenkins testing is configured properly or not

#### Type of change

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

### CODE REVIEW

**Comment by HusnainRazaGhaffar** [comment]
skip ci

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/quality
* jenkins/bokchoy

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/quality
* jenkins/bokchoy

**Comment by HusnainRazaGhaffar** [comment]
jenkins run quality

**Comment by HusnainRazaGhaffar** [comment]
jenkins run bokchoy

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/quality
* jenkins/bokchoy

**Comment by HusnainRazaGhaffar** [comment]
jenkins run bokchoy

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/quality
* jenkins/bokchoy

**Comment by HusnainRazaGhaffar** [comment]
jenkins run quality

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/bokchoy
* jenkins/quality

**Comment by HamzaIbnFarooq** [comment]
jenkins run quality

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python
* jenkins/bokchoy
* jenkins/quality

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/quality
* jenkins/bokchoy

**Comment by HusnainRazaGhaffar** [comment]
jenkins run quality

**Comment by HusnainRazaGhaffar** [comment]
jenkins run quality

**Comment by HusnainRazaGhaffar** [comment]
jenkins run all

**Comment by HusnainRazaGhaffar** [comment]
jenkins run quality

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/bokchoy
* jenkins/quality

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by HusnainRazaGhaffar** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by HusnainRazaGhaffar** [comment]
@HamzaIbnFarooq please don't remove PR #270 and PR #280 yet.

**Comment by tasawernawaz** [comment]
@HamzaIbnFarooq please close this if it is no longer necessary.

**Comment by HusnainRazaGhaffar** [comment]
@HamzaIbnFarooq unit tests are working on other PRs so we can now safely remove this PR

**Pull request closed without merging**
