### PR TITLE
Add code and json files for openassessment.student training assess example example

### PR DESCRIPTION
**Pull request by mumarkhan999**
**Trello Link:** [click here](https://trello.com/c/MuWC3D9V/36-open-response-assessment-event-openassessmentstudenttrainingassessexample)

**Description:** Contains code and current and expected json files for openassessment.student_training_assess_example

**Checks before merge:**

- [ ]  JSON Reviewed
- [ ]   Code Reviewed
- [ ]   Unit Test Pass
- [ ]   Commits squashed

### CODE REVIEW

**Comment by tehreem-sadat** [comment]
@mumarkhan999  Kindly resolve all PEP8 issues.

**Comment by asamolion** [comment]
Wait for the CircleCI build to complete and merge only after it is successful

**Comment by asamolion** [comment]
It failed. Now please debug the issue.

**Comment by mumarkhan999** [comment]
> Wait for the CircleCI build to complete and merge only after it is successful

Ok

**Pull request merged**
