### PR TITLE
Mdandrad/mobile ui improvements

### PR DESCRIPTION
**Pull request by mdandrad**
#### Story Link
https://its-pro.ucsd.edu/browse/EDX-488

#### PR Description

Changes to styling for mobile users
#### Type of change

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

#### How to test?
Please refer to Google do for bugs reported and changes made.  
https://docs.google.com/spreadsheets/d/1o_WJfMqfeR_kAOQpSWX1-FhbCRUdZ9pDry6Ek8Wuvf0/edit#gid=0

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configurations.

- [ ] Test A
- [ ] Test B

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by danialmalik** [comment]
@mdandrad these test failures are not due to your code changes. We have actually fixed the tests in our latest `develop` branch. Could you please rebase your branch with the `develop` branch to make sure that your branch doesn't fail any of the tests?

**Comment by mdandrad** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by mdandrad** [comment]
jenkins run python

**Pull request merged**
