### PR TITLE
[DO NOT MERGE][TESTING] :zap: eventtracking used instead of track utility

### PR DESCRIPTION
**Pull request by danialmalik**

### CODE REVIEW

**Comment by danialmalik** [comment]
jenkins run all

**Comment by danialmalik** [comment]
jenkins run all

**Comment by danialmalik** [comment]
jenkins run python

**Comment by danialmalik** [comment]
jenkins run all

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by m-ali-0001** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by imhassantariq** [comment]
Closing this PR.

**Pull request closed without merging**
