### PR TITLE
release-2020-08-19

### PR DESCRIPTION
**Pull request by danialmalik**
## Release 2020-08-19

- Add bulk email template #414

### CODE REVIEW

**Review by HamzaIbnFarooq — APPROVED** [review]
According to edx, release tag should be `release-2020-08-19`

**Comment by danialmalik** [comment]
@HamzaIbnFarooq if you are referring to `Release 2020-08-19`, the tag will be created later on master branch. Used this just for the PR header

**Comment by HamzaIbnFarooq** [comment]
> @HamzaIbnFarooq if you are referring to `Release 2020-08-19`, the tag will be created later on master branch. Used this just for the PR header
Ok, as you wish but I thought we decided to keep the header same as release tag. #nit

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
