### PR TITLE
Release-2020-04-08 to 2020-04-22

### PR DESCRIPTION
**Pull request by tehreem-sadat**
#### Release code to Prod

**Changes Include**:

- Changes the POST SSO Message and username conflict message. [[Ticket Link](https://edlyio.atlassian.net/browse/EDE-334)] [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/339)]
- Enable search on video transcripts. [[Ticket Link](https://edlyio.atlassian.net/browse/EDE-324)] [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/340)]
- Fix the broken tests. [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/346)]
- Update Version of Xblock Consume LTI. [[Ticket Link](https://edlyio.atlassian.net/browse/EDE-350)] [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/347)]
- Statement of Accomplishment Changings. [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/348)]
- Fix error messages for additional fields added by UCSD. [[Ticket Link](https://edlyio.atlassian.net/browse/EDE-379)][[PR Link](https://github.com/ucsd-ets/edx-platform/pull/349)]
- Bug FIxes:
  - Added LMS_BASE in Production File. [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/352/files)]
  - Fixed LMS_BASE url variable in certificate description.  [[PR Link](https://github.com/ucsd-ets/edx-platform/pull/350)]

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by tehreem-sadat** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by tehreem-sadat** [comment]
jenkins run all

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
