### PR TITLE
Update master with latest develop branch

### PR DESCRIPTION
**Pull request by mdandrad**
#### Story Link
Refer to https://github.com/ucsd-ets/edx-platform/pull/353

#### PR Description

Please include a summary of the change/issue and include relevant information. List any dependencies that are required for this change.

#### Type of change

Please select the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

#### How to test?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configurations.

- [ ] Test A
- [ ] Test B

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Comment by imhassantariq** [comment]
@mdandrad @pjamason Please do not merge the `develop` into `master` directly. We have a release flow for git branching.

`develop` -> `release-candidate` -> `master`

First, we make our changes in the `develop` then merge it into `release-candidate` every week.  After successful QA on stage server, we merge it into `master` then we create a release tag and deploy it onto `Production`

Here is the link of Flow we follow: https://docs.google.com/document/d/1QTrCMYnGgr5q5ayw62ZYqneWecffBXvEBqIpua3co0M/edit?usp=sharing

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by pjamason** [comment]
closing without merging - sorry about that @imhassantariq

**Pull request closed without merging**
