### PR TITLE
EDS-233: Fixing python tests

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### Story Link
[EDS-233](https://edlyio.atlassian.net/browse/EDS-233)

#### PR Description

After configuring python tests for edx-platform, we came to know that a few tests are failing. This PR is meant to fix all those tests.

[List of currently failing tests](https://jens-learnx-dev.ucsd.edu/job/edx-platform-python-pipeline-pr/57/)

#### Type of change

Please select the options that are relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Change

#### How to test?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configurations.

- [ ] Test A
- [ ] Test B

#### Checklist before merging:

- [ ] Squased
- [ ] Reviewd

### CODE REVIEW

**Comment by HamzaIbnFarooq** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HamzaIbnFarooq** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. The following contexts failed:
* jenkins/python

**Comment by HamzaIbnFarooq** [comment]
jenkins run python

**Comment by HamzaIbnFarooq** [comment]
jenkins run python

**Comment by edtecheco** [comment]
Your PR has finished running tests. There were no failures.

**Pull request merged**
